name: 'Publish Release'

on:
  push:
    tags:  ['**']

jobs:
  pypi_build:
    name: 'PyPi Package Build and Publish'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Setup python'
        uses: 'actions/setup-python@v2'
        with:
          python-version: '3.9'
      - name: 'Install PiPy dependencies'
        run: |
          python -m pip install --upgrade build pip twine
      - name: 'Remove v from the tag'
        id: 'publish-version'
        run: |
          VERSION=$(echo "${GITHUB_REF/refs\/tags\//}" | sed 's/^.//')
          echo "::set-output name=version::${VERSION}"
      - name: 'Generate VERSION.txt'
        run: |
          echo "${{ steps.publish-version.outputs.version }}" > VERSION.txt
      - name: 'Build'
        run: |
          python -m build --sdist --wheel .
      - name: 'Publish'
        run: |
          echo "[pypi]
          username = __token__
          password = ${{ secrets.PYPI_PROD }}" > ~/.pypirc
          python -m twine upload dist/*
